### ISSUE TITLE
Error occurred when executing LivePortraitProcess

### ISSUE THREAD

**Issue by mdkid79** [kijai/ComfyUI-LivePortraitKJ#15] opened 2024-07-05 14:56 UTC
Error occurred when executing LivePortraitProcess:

D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:636 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\nodes.py", line 247, in process
cropper = Cropper(crop_cfg=crop_cfg)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\utils\cropper.py", line 39, in __init__
self.landmark_runner = LandmarkRunner(
^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ\liveportrait\utils\landmark_runner.py", line 36, in __init__
self.session = onnxruntime.InferenceSession(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 394, in __init__
raise fallback_error from e
File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 389, in __init__
self._create_inference_session(self._fallback_providers, None)
File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 435, in _create_inference_session
sess.initialize_session(providers, provider_options, disabled_optimizers)

how should I install CUDA or find the PATH to add it in system
thanks

**Comment by mdkid79** [comment] 2024-07-07 07:31
solved it

**Comment by ElevatedKitten** [comment] 2024-07-07 07:43
And how did you solve it? I have the same problem.

**Comment by mdkid79** [comment] 2024-07-07 17:21
> And how did you solve it? I have the same problem.

Two days ago, I just update the CUDA to 12.5
So I think that maybe the problem 
Then I uninstall 12.5 and delete all connect file and reinstall CUDA 12.4 and cuDDN 9.8 
It work, you can try it
Good luck!

**Comment by kijai** [comment] 2024-07-08 13:25
> i absolutely despise that how bad comfyui is for beginners, tried everything from every video and internet but this error doesnt seem to go away. im on cuda 12.4 and cuddn 8.9.2 , nothing works

This doesn't really have anything to do with ComfyUI itself though, the error comes from onnx which is used by insightface, which is used by the LivePortrait code. These are the usual Python dependency issues that are hard to deal with even with experience.

As such it's bit hard for me to reproduce and offer guidance about, I've been trying but can't get this error to happen. You would have to refer to onnxruntime info about the subject:
https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirements

**Comment by kijai** [comment] 2024-07-08 13:46
Added option to select the onnx device, seems fast on CPU too and maybe easier to run? 
![image](https://github.com/kijai/ComfyUI-LivePortraitKJ/assets/40791699/42336541-19a3-49d7-889d-ccd335b4eb1c)

**Comment by Vashthareaper** [comment] 2024-07-08 14:59
will try this thank you so much, sorry about the rant, i got too frustrated trying to resolve this issue unrelated to your work and more towards onnx, and thank you so much for your work

**Comment by Vashthareaper** [comment] 2024-07-08 15:03
cpu is working great, tysm for quick response

**Comment by mdkid79** [comment] 2024-07-08 15:03
onnxruntime is 1.8……but not just this node has issues like this, I have a similar problem on other node
By the way, I am not a programmer
Actually, I even don't understand what truly problem with that
I just search it on google😂

**Comment by Vashthareaper** [comment] 2024-07-08 15:04
> Author

update the node in comfyui manager and now it has the cpu option, just as fast tbh and dont have to deal with resolving this issue, i have been trying all morning

**Comment by kijai** [comment] 2024-07-08 15:07
Great, I don't really understand why they default to cuda in the first place, might have something to do with the video editing feature they didn't release yet.

**Comment by mdkid79** [comment] 2024-07-08 15:19
So great

**Closed** 2024-07-09 06:17 UTC

**Comment by Vashthareaper** [comment] 2024-07-11 12:39
For anyone who might face an issue relating cuda not loading , here is what i did , hope this helps

here is what i did exactly to fix this annoying issue for comfyui

1- Starting from scratch
1 - deleted cuda from program files >> Nvidia GPU toolkit
2 - im a noob so installed 3 different python versions (deleted all but only kept python 3.10)
3 - deleted every extra version of visual studio and only kept visual studio 2015-2022 + visual studio community 2022

2- Installation (installed Anaconda alongside pip)
1 - Installed pytorch , ran these two commands in anaconda
conda install pytorch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 pytorch-cuda=11.8 -c pytorch -c nvidia
pip install torch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 --index-url https://download.pytorch.org/whl/cu118

  2 - downloaded cuda toolkit 11.8 and cuddn 8.9.2 and followed this video for installation (https://www.youtube.com/watch?v=ctQi9mU7t9o&t=642s) , please watch it full as you have to copy paste files for cuddn to conda dir, and set paths in environmental variables.
  3 - ran this command for tensorflow      pip install tensorflow

Please ignore my lack of knowlege as ive only been using comfyui or even downloded python for first time last week. it took me 2 days to figure this out but i realised downloading exact versions for everything do matter. Hope this helps anyone still struggling with cuda not loaded for Onnxruntime

**Comment by emperor1412** [comment] 2024-07-24 11:19
> Added option to select the onnx device, seems fast on CPU too and maybe easier to run? ![image](https://private-user-images.githubusercontent.com/40791699/346586962-42336541-19a3-49d7-889d-ccd335b4eb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAwMDgsIm5iZiI6MTcyMTgxOTcwOCwicGF0aCI6Ii80MDc5MTY5OS8zNDY1ODY5NjItNDIzMzY1NDEtMTlhMy00OWQ3LTg4OWQtY2NkMzM1YjRlYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTNkNzc0NGEwY2U4NzViYmRmZGVlMjMwZGRiNTc4ZTdlYzdkY2RiYmU1ZGNiMmMzZjA3NmU0MzMzNDJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXlCzVOqwu524PK5i0oeGEBmHeJNvVAURwtsVsjQ4ms)

Hi, I had this selected with CUDA, but looks like it always utilize 100% of CPU, is this a bug or so?

`LandmarkRunner warmup time: 0.108s
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (512, 512)
FaceAnalysisDIY warmup time: 0.041s
Detecting, cropping, and processing..:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌               | 132/150 [02:00<00:14,  1.24it/s]`

**Comment by kijai** [comment] 2024-07-24 11:21
> > Added option to select the onnx device, seems fast on CPU too and maybe easier to run? ![image](https://private-user-images.githubusercontent.com/40791699/346586962-42336541-19a3-49d7-889d-ccd335b4eb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAwMDgsIm5iZiI6MTcyMTgxOTcwOCwicGF0aCI6Ii80MDc5MTY5OS8zNDY1ODY5NjItNDIzMzY1NDEtMTlhMy00OWQ3LTg4OWQtY2NkMzM1YjRlYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTNkNzc0NGEwY2U4NzViYmRmZGVlMjMwZGRiNTc4ZTdlYzdkY2RiYmU1ZGNiMmMzZjA3NmU0MzMzNDJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXlCzVOqwu524PK5i0oeGEBmHeJNvVAURwtsVsjQ4ms)
> 
> Hi, I had this selected with CUDA, but looks like it always utilize 100% of CPU, is this a bug or so?
> 
> `LandmarkRunner warmup time: 0.108s Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (512, 512) FaceAnalysisDIY warmup time: 0.041s Detecting, cropping, and processing..: 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 132/150 [02:00<00:14, 1.24it/s]`

It will default to CPU if it can't use CUDA, do you have onnxruntime-gpu installed?

**Comment by emperor1412** [comment] 2024-07-24 11:24
> > > Added option to select the onnx device, seems fast on CPU too and maybe easier to run? ![image](https://private-user-images.githubusercontent.com/40791699/346586962-42336541-19a3-49d7-889d-ccd335b4eb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAwMDgsIm5iZiI6MTcyMTgxOTcwOCwicGF0aCI6Ii80MDc5MTY5OS8zNDY1ODY5NjItNDIzMzY1NDEtMTlhMy00OWQ3LTg4OWQtY2NkMzM1YjRlYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTNkNzc0NGEwY2U4NzViYmRmZGVlMjMwZGRiNTc4ZTdlYzdkY2RiYmU1ZGNiMmMzZjA3NmU0MzMzNDJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXlCzVOqwu524PK5i0oeGEBmHeJNvVAURwtsVsjQ4ms)
> > 
> > 
> > Hi, I had this selected with CUDA, but looks like it always utilize 100% of CPU, is this a bug or so?
> > `LandmarkRunner warmup time: 0.108s Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (512, 512) FaceAnalysisDIY warmup time: 0.041s Detecting, cropping, and processing..: 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 132/150 [02:00<00:14, 1.24it/s]`
> 
> It will default to CPU if it can't use CUDA, do you have onnxruntime-gpu installed?

Yes I have gpu version installed

onnx                         1.16.1
onnxruntime                  1.18.1
onnxruntime-gpu              1.18.0

![image](https://github.com/user-attachments/assets/ec4c4a75-0784-426b-871e-173e6de50a41)


I even try to modify code to force use CUDA but nothing changed, perhaps I'm touching the wrong file

**Comment by kijai** [comment] 2024-07-24 11:51
> > > > Added option to select the onnx device, seems fast on CPU too and maybe easier to run? ![image](https://private-user-images.githubusercontent.com/40791699/346586962-42336541-19a3-49d7-889d-ccd335b4eb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAwMDgsIm5iZiI6MTcyMTgxOTcwOCwicGF0aCI6Ii80MDc5MTY5OS8zNDY1ODY5NjItNDIzMzY1NDEtMTlhMy00OWQ3LTg4OWQtY2NkMzM1YjRlYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTNkNzc0NGEwY2U4NzViYmRmZGVlMjMwZGRiNTc4ZTdlYzdkY2RiYmU1ZGNiMmMzZjA3NmU0MzMzNDJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXlCzVOqwu524PK5i0oeGEBmHeJNvVAURwtsVsjQ4ms)
> > > 
> > > 
> > > Hi, I had this selected with CUDA, but looks like it always utilize 100% of CPU, is this a bug or so?
> > > `LandmarkRunner warmup time: 0.108s Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (512, 512) FaceAnalysisDIY warmup time: 0.041s Detecting, cropping, and processing..: 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 132/150 [02:00<00:14, 1.24it/s]`
> > 
> > 
> > It will default to CPU if it can't use CUDA, do you have onnxruntime-gpu installed?
> 
> Yes I have gpu version installed
> 
> onnx 1.16.1 onnxruntime 1.18.1 onnxruntime-gpu 1.18.0
> 
> ![image](https://private-user-images.githubusercontent.com/930373/351694553-ec4c4a75-0784-426b-871e-173e6de50a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjIwOTgsIm5iZiI6MTcyMTgyMTc5OCwicGF0aCI6Ii85MzAzNzMvMzUxNjk0NTUzLWVjNGM0YTc1LTA3ODQtNDI2Yi04NzFlLTE3M2U2ZGU1MGE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMTQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWZmYmZiOTc1MTk3OTFmMzk5ZmM3N2VmZjg1NWEyMjc0NDY4NmMwYmFhYjkzMDQ1MTA4ZDQyZGUwM2RlYWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y-yqKfcR75hH3vShmFt2KRDaokvQlozlLhjklxHV8ao)
> 
> I even try to modify code to force use CUDA but nothing changed, perhaps I'm touching the wrong file

Won't help to try to force it, it absolutely works with CUDA selected as long as everything it requires is setup. It's generally an onnx issue and probably something incompatible with it.

**Comment by emperor1412** [comment] 2024-07-24 14:33
> > > > > Added option to select the onnx device, seems fast on CPU too and maybe easier to run? ![image](https://private-user-images.githubusercontent.com/40791699/346586962-42336541-19a3-49d7-889d-ccd335b4eb1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjAwMDgsIm5iZiI6MTcyMTgxOTcwOCwicGF0aCI6Ii80MDc5MTY5OS8zNDY1ODY5NjItNDIzMzY1NDEtMTlhMy00OWQ3LTg4OWQtY2NkMzM1YjRlYjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExMTUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMTNkNzc0NGEwY2U4NzViYmRmZGVlMjMwZGRiNTc4ZTdlYzdkY2RiYmU1ZGNiMmMzZjA3NmU0MzMzNDJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qXlCzVOqwu524PK5i0oeGEBmHeJNvVAURwtsVsjQ4ms)
> > > > 
> > > > 
> > > > Hi, I had this selected with CUDA, but looks like it always utilize 100% of CPU, is this a bug or so?
> > > > `LandmarkRunner warmup time: 0.108s Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0 Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}} find model: F:\ComfyUI\ComfyUI\models\insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5 set det-size: (512, 512) FaceAnalysisDIY warmup time: 0.041s Detecting, cropping, and processing..: 88%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 132/150 [02:00<00:14, 1.24it/s]`
> > > 
> > > 
> > > It will default to CPU if it can't use CUDA, do you have onnxruntime-gpu installed?
> > 
> > 
> > Yes I have gpu version installed
> > onnx 1.16.1 onnxruntime 1.18.1 onnxruntime-gpu 1.18.0
> > ![image](https://private-user-images.githubusercontent.com/930373/351694553-ec4c4a75-0784-426b-871e-173e6de50a41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjIwOTgsIm5iZiI6MTcyMTgyMTc5OCwicGF0aCI6Ii85MzAzNzMvMzUxNjk0NTUzLWVjNGM0YTc1LTA3ODQtNDI2Yi04NzFlLTE3M2U2ZGU1MGE0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQxMTQ5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWZmYmZiOTc1MTk3OTFmMzk5ZmM3N2VmZjg1NWEyMjc0NDY4NmMwYmFhYjkzMDQ1MTA4ZDQyZGUwM2RlYWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Y-yqKfcR75hH3vShmFt2KRDaokvQlozlLhjklxHV8ao)
> > I even try to modify code to force use CUDA but nothing changed, perhaps I'm touching the wrong file
> 
> Won't help to try to force it, it absolutely works with CUDA selected as long as everything it requires is setup. It's generally an onnx issue and probably something incompatible with it.

Thanks for the suggestions, I resolved it by installing cudnn and add it to environment path.
